### ISSUE TITLE
House Leaderboard

### ISSUE THREAD

**Issue by miriamhaenle** [macfrei/harry-potter-app#1]
**Value Statement**
As a student
I want to see the ranking of the houses
so that I know which house wins the school cup.

**Description:**
<img width="435" alt="Screenshot 2020-11-22 at 20 23 57" src="https://user-images.githubusercontent.com/60315975/99914890-abc50d80-2d00-11eb-8bb5-abdcb3985369.png">

**Acceptance Criteria: **

- [ ]  List of all four houses is displayed with total house points per house
- [ ]  List is ordered my house points (the house with most points on top)

**Tasks: **
- [ ] Create feature branch
- [ ]  Create Button component
- [ ]  Create LeaderBoard component
- [ ]  Create Header component
- [ ]  Write unit tests
- [ ]  Write component tests
- [ ]  Write integration tests w/ Cypress
